## Numpy入门

In [2]:
import numpy as np

In [3]:
# List
list_a = [1, 2, 3]
list_b = [3, 2, 1]
print(list_a, type(list_a))
print(list_b, type(list_b))

# 1D
np_a = np.array(list_a)
np_b = np.array(list_b)
print(np_a, type(np_a))
print(np_b, type(np_b))

# 2D
A = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
B = np.array([[3, 2, 1], [3, 2, 1], [3, 2, 1]])
print(A, type(A)) 
print(B, type(B))

[1, 2, 3] <class 'list'>
[3, 2, 1] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>
[3 2 1] <class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>
[[3 2 1]
 [3 2 1]
 [3 2 1]] <class 'numpy.ndarray'>


###  List vs NumPy 差异

In [4]:
# + 对照
print("== 加法 ==")
print("list_a + list_b =\n", list_a + list_b)
print("np_a + np_b =\n", np_a + np_b)
print("A + B =\n", A + B)

# * 对照
print("== 乘法 ==")
print("list_a * 2 =\n", list_a * 2)
print("np_a * 2 =\n", np_a * 2)
print("A * B =\n", A * B)

== 加法 ==
list_a + list_b =
 [1, 2, 3, 3, 2, 1]
np_a + np_b =
 [4 4 4]
A + B =
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
== 乘法 ==
list_a * 2 =
 [1, 2, 3, 1, 2, 3]
np_a * 2 =
 [2 4 6]
A * B =
 [[3 4 3]
 [3 4 3]
 [3 4 3]]


### 矩阵基本运算
- 官方文档: https://numpy.org/doc/stable/reference/index.html
- 中文教程：https://www.runoob.com/numpy/numpy-tutorial.html

#### 向量计算

In [5]:
u = np.array([1, 2, 3])
v = np.array([3, 2, 1])

In [8]:
# TODO: 两种方式（符号@、numpy api）计算向量 u 与 v 的“内积”
# - 内积：对应位置元素相乘后求和，结果是一个标量
inner_uv_1 = u@v
inner_uv_2 = np.inner(u, v)
print("Inner product:", inner_uv_1, inner_uv_2)


# TODO: 使用numpy api计算向量 u 与 v 的“外积”
# - 外积：得到一个矩阵，矩阵第 (i,j) 项 = u[i] * v[j]
outer_uv = np.outer(u, v)
print("Outer product: ", outer_uv)


# TODO: 两种方式（numpy api / 自行等价实现）计算向量的 L2 范数（欧几里得长度）
# - L2 范数：sqrt(sum(u[i]^2))
norm_u_1 = np.linalg.norm(u - v)
norm_u_2 = np.sqrt(np.sum(np.square(u - v)))
print("||u||:", norm_u_1, norm_u_2)

# 将 NumPy 数组转换回 Python list 形式，并输出
print("outer_uv as python list:", outer_uv.tolist())
print("Type: ", type(outer_uv.tolist()))
      

Inner product: 10 10
Outer product:  [[3 2 1]
 [6 4 2]
 [9 6 3]]
||u||: 2.8284271247461903 2.8284271247461903
outer_uv as python list: [[3, 2, 1], [6, 4, 2], [9, 6, 3]]
Type:  <class 'list'>


#### 矩阵计算

In [9]:
A = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
B = np.array([[3, 2, 1], [3, 2, 1], [3, 2, 1]])

In [11]:
# TODO: 输出矩阵 A 与 B 的 shape（形状），用于确认矩阵维度是否匹配
print("A's shape =", A, "B.shape =", B)

# TODO: 两种方式（符号+、numpy api）计算矩阵加法 A + B（逐元素相加）
add_AB_1 = A + B
add_AB_2 = np.add(A, B)
print("A + B:\n", add_AB_1)
print("A + B:\n", add_AB_2)
print()

# TODO: 两种方式（符号*、numpy api）计算 element-wise 乘法 A * B（逐元素相乘）
elem_mul_AB_1 = A * B
elem_mul_AB_2 = np.multiply(A, B)
print("A * B (element-wise):\n", elem_mul_AB_1)
print("A * B (element-wise):\n", elem_mul_AB_2)
print()

# TODO: 两种方式（符号@、numpy api）计算矩阵乘法（matrix product）
# - 矩阵乘法：结果第 (i,j) 项 = A 第 i 行 与 B 第 j 列 的内积
mat_mul_AB_1 = A@B
mat_mul_AB_2 = np.dot(A, B)
print("matrix product:\n", mat_mul_AB_1)
print("matrix product:\n", mat_mul_AB_2)
print()

# TODO: 两种方式（符号.T、numpy api）计算矩阵转置（行列互换）
AT_1 = A.T
AT_2 = np.transpose(A)
print("A.T:\n", AT_1)
print("A.T:\n", AT_2)

A's shape = [[1 2 3]
 [1 2 3]
 [1 2 3]] B.shape = [[3 2 1]
 [3 2 1]
 [3 2 1]]
A + B:
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
A + B:
 [[4 4 4]
 [4 4 4]
 [4 4 4]]

A * B (element-wise):
 [[3 4 3]
 [3 4 3]
 [3 4 3]]
A * B (element-wise):
 [[3 4 3]
 [3 4 3]
 [3 4 3]]

matrix product:
 [[18 12  6]
 [18 12  6]
 [18 12  6]]
matrix product:
 [[18 12  6]
 [18 12  6]
 [18 12  6]]

A.T:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
A.T:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]


## 矩阵进阶运算

In [12]:
X = np.array([[1, 2, 4],[5, 4, 7],[9, 0, 8]])
b = np.array([10, 20, 30]) 

In [16]:
print("X.shape =", X.shape, "b.shape =", b.shape)

# TODO: 两种方式（符号+、numpy api）计算矩阵 X 与向量 b 的加法 X + b，并观察当维度不匹配时，NumPy 是如何计算的
Y_1 = X + b
Y_2 = np.add(X, b)
print("\nY = X + b:\n", Y_1)
print("\nY = X + b:\n", Y_2)

# TODO: 使用 numpy api 计算结果每一「行」的和 row_sum，并保持二维矩阵的形状
row_sum = X.sum(axis=1, keepdims=True)
print("\nrow_sum:\n", row_sum, "\nshape:", row_sum.shape)

# TODO: 两种方式（符号/、numpy api）做“按行归一化”，使得每行和为 1
Y_norm_1 = X / row_sum
Y_norm_2 = np.divide(X, row_sum)
print("\nY_norm :\n", Y_norm_1)
print("\nY_norm :\n", Y_norm_2)

X.shape = (3, 3) b.shape = (3,)

Y = X + b:
 [[11 22 34]
 [15 24 37]
 [19 20 38]]

Y = X + b:
 [[11 22 34]
 [15 24 37]
 [19 20 38]]

row_sum:
 [[ 7]
 [16]
 [17]] 
shape: (3, 1)

Y_norm :
 [[0.14285714 0.28571429 0.57142857]
 [0.3125     0.25       0.4375    ]
 [0.52941176 0.         0.47058824]]

Y_norm :
 [[0.14285714 0.28571429 0.57142857]
 [0.3125     0.25       0.4375    ]
 [0.52941176 0.         0.47058824]]


## 矩阵数据处理

In [17]:
X = np.array([[1, 2, 4],[5, 4, 7],[9, 0, 8]])

# TODO: 切片（slicing）取子矩阵：取 X 的前两列。两种方式：直接索引 / numpy api
sub1_1 = X[:2:]
sub1_2 = X[slice(2)]
print("\n Slicing =\n", sub1_1)
print("\n Slicing =\n", sub1_2)

# TODO: 计算每「行」均值，两种方式：ndarray 方法 / numpy api
row_mean_1 = X.mean(axis=1)
row_mean_2 = np.mean(X, axis=1)
print("\nmean =", row_mean_1)
print("\nmean =", row_mean_2)

# TODO: 计算每「列」求和，两种方式：ndarray 方法 / numpy api
col_sum_1 = X.mean(axis=0)
col_sum_2 = np.mean(X, axis=0)
print("\nsum =", col_sum_1)
print("\nsum =", col_sum_2)

# TODO: 计算每「行」最大值的索引，两种方式：ndarray 方法 / numpy api
row_argmax_1 = X.argmax(axis=1)
row_argmax_2 = np.argmax(X, axis=1)
print("\nargmax =", row_argmax_1)
print("\nargmax =", row_argmax_2)


 Slicing =
 [[1 2 4]
 [5 4 7]]

 Slicing =
 [[1 2 4]
 [5 4 7]]

mean = [2.33333333 5.33333333 5.66666667]

mean = [2.33333333 5.33333333 5.66666667]

sum = [5.         2.         6.33333333]

sum = [5.         2.         6.33333333]

argmax = [2 2 0]

argmax = [2 2 0]
